apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations: 
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: www.exemple.com
    http:
      paths:
        - path: /users
          pathType: "Prefix"
          backend:
            serviceName: user-service
            servicePort: 80
        - path: /customer
          pathType: "Prefix"
          backend:
            serviceName: customer-service
            servicePort: 80



  