apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: user-deployment
  template:
    metadata:
      labels:
        run: user-deployment
    spec:
      containers:
        - name: userservices
          image: azizg/azizgaamouz:userservice
          resources:
            limits: 
              cpu: 100m
              memory: 500Mi
      imagePullSecrets: 
        - name: regcred
        
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    run: user-deployment
  ports:
    - port: 80